version: '3.8'

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: dbkatana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  php-fpm:
    build: ./app
    depends_on:
      - postgres

  nginx: 
    image: nginx:latest
    volumes: 
    - ./app:/var/www/html
    - ./docker/nginx/config/symfony.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8000:80
    depends_on:
      - php-fpm

  react:
    build: ./front
    ports:
      - 5173:5173
    environment:
      - VITE_API_SCHEME=http